 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/customers', type: :request do
  describe 'Get /customers' do
    it 'works!' do
      get customers_path
      expect(response).to have_http_status(200)
    end

    it 'JSON works!' do
      get('/customers.json')
      expect(response).to have_http_status(200)
      expect(response.body).to include_json([
          id: /\d/,
          name: (be_kind_of String),
          email: (be_kind_of String)
      ])
    end

    it 'show - JSON works!' do
      get('/customers/1.json')
      expect(response).to have_http_status(200)
      expect(response.body).to include_json(
        id: 1,
        name: (be_kind_of String),
        email: (be_kind_of String)
      )
    end
  end
end
